ignore:
    - "include/external"
    - "programs"
    - "single_include"
    - "single_include_test"
    - "tests"
coverage:
    status:
        project:
            default:
                target: 85%