# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csv-parser

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csv-parser

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csv-parser/CMakeFiles /home/csv-parser/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csv-parser/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doxygen

# Build rule for target.
doxygen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doxygen
.PHONY : doxygen

# fast build rule for target.
doxygen/fast:
	$(MAKE) -f CMakeFiles/doxygen.dir/build.make CMakeFiles/doxygen.dir/build
.PHONY : doxygen/fast

#=============================================================================
# Target rules for targets named csv

# Build rule for target.
csv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csv
.PHONY : csv

# fast build rule for target.
csv/fast:
	$(MAKE) -f include/internal/CMakeFiles/csv.dir/build.make include/internal/CMakeFiles/csv.dir/build
.PHONY : csv/fast

#=============================================================================
# Target rules for targets named csv_bench

# Build rule for target.
csv_bench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csv_bench
.PHONY : csv_bench

# fast build rule for target.
csv_bench/fast:
	$(MAKE) -f programs/CMakeFiles/csv_bench.dir/build.make programs/CMakeFiles/csv_bench.dir/build
.PHONY : csv_bench/fast

#=============================================================================
# Target rules for targets named csv_guess_bench

# Build rule for target.
csv_guess_bench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csv_guess_bench
.PHONY : csv_guess_bench

# fast build rule for target.
csv_guess_bench/fast:
	$(MAKE) -f programs/CMakeFiles/csv_guess_bench.dir/build.make programs/CMakeFiles/csv_guess_bench.dir/build
.PHONY : csv_guess_bench/fast

#=============================================================================
# Target rules for targets named csv_stats

# Build rule for target.
csv_stats: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csv_stats
.PHONY : csv_stats

# fast build rule for target.
csv_stats/fast:
	$(MAKE) -f programs/CMakeFiles/csv_stats.dir/build.make programs/CMakeFiles/csv_stats.dir/build
.PHONY : csv_stats/fast

#=============================================================================
# Target rules for targets named csv_info

# Build rule for target.
csv_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csv_info
.PHONY : csv_info

# fast build rule for target.
csv_info/fast:
	$(MAKE) -f programs/CMakeFiles/csv_info.dir/build.make programs/CMakeFiles/csv_info.dir/build
.PHONY : csv_info/fast

#=============================================================================
# Target rules for targets named generate_csv_bench

# Build rule for target.
generate_csv_bench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate_csv_bench
.PHONY : generate_csv_bench

# fast build rule for target.
generate_csv_bench/fast:
	$(MAKE) -f programs/CMakeFiles/generate_csv_bench.dir/build.make programs/CMakeFiles/generate_csv_bench.dir/build
.PHONY : generate_csv_bench/fast

#=============================================================================
# Target rules for targets named data_type_bench

# Build rule for target.
data_type_bench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 data_type_bench
.PHONY : data_type_bench

# fast build rule for target.
data_type_bench/fast:
	$(MAKE) -f programs/CMakeFiles/data_type_bench.dir/build.make programs/CMakeFiles/data_type_bench.dir/build
.PHONY : data_type_bench/fast

#=============================================================================
# Target rules for targets named generate_dtype_bench

# Build rule for target.
generate_dtype_bench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate_dtype_bench
.PHONY : generate_dtype_bench

# fast build rule for target.
generate_dtype_bench/fast:
	$(MAKE) -f programs/CMakeFiles/generate_dtype_bench.dir/build.make programs/CMakeFiles/generate_dtype_bench.dir/build
.PHONY : generate_dtype_bench/fast

#=============================================================================
# Target rules for targets named csv_generator

# Build rule for target.
csv_generator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csv_generator
.PHONY : csv_generator

# fast build rule for target.
csv_generator/fast:
	$(MAKE) -f programs/CMakeFiles/csv_generator.dir/build.make programs/CMakeFiles/csv_generator.dir/build
.PHONY : csv_generator/fast

#=============================================================================
# Target rules for targets named csv_coverage

# Build rule for target.
csv_coverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csv_coverage
.PHONY : csv_coverage

# fast build rule for target.
csv_coverage/fast:
	$(MAKE) -f tests/CMakeFiles/csv_coverage.dir/build.make tests/CMakeFiles/csv_coverage.dir/build
.PHONY : csv_coverage/fast

#=============================================================================
# Target rules for targets named csv_test

# Build rule for target.
csv_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csv_test
.PHONY : csv_test

# fast build rule for target.
csv_test/fast:
	$(MAKE) -f tests/CMakeFiles/csv_test.dir/build.make tests/CMakeFiles/csv_test.dir/build
.PHONY : csv_test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... doxygen"
	@echo "... csv"
	@echo "... csv_bench"
	@echo "... csv_guess_bench"
	@echo "... csv_stats"
	@echo "... csv_info"
	@echo "... generate_csv_bench"
	@echo "... data_type_bench"
	@echo "... generate_dtype_bench"
	@echo "... csv_generator"
	@echo "... csv_coverage"
	@echo "... csv_test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

